- name: Install docker using Ansible Playbook
  hosts: docker
  become: true
  tasks:
    - name: Install docker package
      package:
        name: docker
        state: present

    - name: Start and enable docker service
      service:
        name: docker
        state: started


- name: Install httpd using Ansible Playbook
  hosts: httpd
  become: true
  tasks:
    - name: Install httpd package
      package:
        name: httpd
        state: present
